// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ta4rhC2-cgNcvxw55GZeZvLrsghTRG0',
    appId: '1:955906548828:web:454b6782cf9a0a23ddf299',
    messagingSenderId: '955906548828',
    projectId: 'chat-project-512bb',
    authDomain: 'chat-project-512bb.firebaseapp.com',
    storageBucket: 'chat-project-512bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSXUehBUKc7G-hsLq5LYYhD6jjuJJVIeY',
    appId: '1:955906548828:android:4aab49c3676ff022ddf299',
    messagingSenderId: '955906548828',
    projectId: 'chat-project-512bb',
    storageBucket: 'chat-project-512bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp2vNt-l5kz4mwVv3SLsqCROyrkcF6TaY',
    appId: '1:955906548828:ios:9cd5ab7b6ddc1d7dddf299',
    messagingSenderId: '955906548828',
    projectId: 'chat-project-512bb',
    storageBucket: 'chat-project-512bb.appspot.com',
    iosClientId: '955906548828-5c4tork23b86ksl7hfbsg2o4oc62ptna.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkApp',
  );
}
