name: alfred_backend

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  alfred:
  postgres: ^3.2.0
  dart_openai: ^5.1.0
  dotenv: ^4.2.0
  http: ^1.2.1
  gcloud: ^0.8.12
  googleapis_auth: ^1.6.0
  uuid: ^4.4.0
  audioplayers: ^6.0.0





